title: DeepPheWAS
description: A website to descibe the features of DeepPheWAS.R an R package for performing phenome wide association studies.
theme: just-the-docs

url: https://richard-packer.github.io/DeepPheWAS_site/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
