title: DeepPheWAS
description: A website to descibe the features of DeepPheWAS.R an R package for performing phenome wide association studies.
theme: just-the-docs

url: https://richard-packer.github.io/DeepPheWAS_site/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

port: 4444

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Aux links for the upper right navigation
aux_links:
  "DeepPheWAS on GitHub":
    - "//github.com/Richard-Packer/DeepPheWAS"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
#color_scheme: dark

# For copy button on code
enable_copy_code_button: true

plugins:
  - jekyll-target-blank

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
